### ISSUE TITLE
no -mno-cygwin option support prevents Mercurial build

### ISSUE THREAD

**Issue by jonforums** [rubenvb/MinGW-w64-build-scripts#1]
When using i686-w64-mingw32-gcc-4.6.2_rubenvb.7z to try to build Mercurial on Win7 32bit I get the following build failure

http://pastie.org/2274486

Is this a build configuration issue, a 4.6.2 issue, or my setup?

**Comment by rubenvb** [comment]
the option "-mno-cygwin" has been removed from GCC some time ago.

This is Mercurial's problem to fix.

**Comment by jonforums** [comment]
> the option "-mno-cygwin" has been removed from GCC some time ago.

This doesn't appear to be true. As of the `mingw-w32-1.0-bin_i686-mingw_20110624.zip` download (with exes renamed) with

```
C:\mercurial\mercurial-stable>gcc --version
gcc (GCC) 4.5.4 20110624 (prerelease)
```

I get this http://pastie.org/2270300  While it errors out for another reason, it appears to support `-mno-cygwin`

Regardless, this isn't a Mercurial problem as any cleanup would need to occur in Python's distutils, likely around here

http://hg.python.org/cpython/file/4feb889d3bed/Lib/distutils/cygwinccompiler.py#l296

Is there a way to configure your build so it simply ignores `-mno-cygwin` rather than fails?

**Comment by jonforums** [comment]
fyi, submitted new bug report to Python http://bugs.python.org/issue12641

**Comment by rubenvb** [comment]
Well, here's a discussion about it being removed:

http://www.mail-archive.com/cygwin@cygwin.com/msg95408.html

That was March 2009, and there are other references on several mailing lists and bugtrackers.

The GCC commit removing this option is this one (I'll add the link to the Python bug): http://repo.or.cz/w/official-gcc.git/commit/2637551aa9314c46cf4205d435ab5e8944e9ac8a

if it's in distutils, it's Python's issue, and should have been fixed a long time ago.

Nothing I can do about it, it has been forcibly removed from GCC, and that is a good thing.
