### ISSUE TITLE
Make - job server support

### ISSUE THREAD

**Issue by net147** [rubenvb/MinGW-w64-build-scripts#15]
It would be good if you included job server support for make 3.82:
http://www.mail-archive.com/make-w32@gnu.org/msg02283.html

Alternatively you could build make from CVS version.
It's useful for doing parallel builds with set MAKEFLAGS=-j%NUMBER_OF_PROCESSORS%.

**Comment by rubenvb** [comment]
Hmm... I applied the make patches in the official MinGW-w64 make package, but it seems those patches weren't as complete as the one you linked to. I will see to it in the next release.

**Comment by net147** [comment]
Any update on this?

**Comment by rubenvb** [comment]
I applied this patch to the last (2?) builds: https://github.com/rubenvb/MinGW-w64-build-scripts/blob/master/toolchain/patches/make-windows.patch

It is a all-in-one patch made up of the ones you linked to. For sure the 4.7.0-1 release has this.

**Comment by net147** [comment]
Your patch is different.

**Comment by net147** [comment]
Patch still isn't included: http://www.mail-archive.com/make-w32@gnu.org/msg02283/windows_jobserver.diff

**Comment by rubenvb** [comment]
I have included the additional patch in my build. It is certainly in the 4.6.4 release, I think I also put it in the 4.7.0-2 build (not sure though).
