### ISSUE TITLE
_ftime x64 CRT header fix

### ISSUE THREAD

**Issue by net147** [rubenvb/MinGW-w64-build-scripts#16]
Please include _ftime header fix: http://sourceforge.net/tracker/?func=detail&atid=983354&aid=3456848&group_id=202880.
This fixes OpenSSL and WebKit timer accuracy. On Qt 4.8.0, this fixes JavaScript timer accuracy being reduced to around 1 second and autoscroll using middle mouse button lagging.

**Comment by rubenvb** [comment]
I'll see if this fix can also bee applied on at least the v2.x branch.

**Comment by net147** [comment]
Any update on this?

**Comment by rubenvb** [comment]
http://sourceforge.net/tracker/?func=detail&atid=983354&aid=3456848&group_id=202880

says it has been applied some time ago.
