### ISSUE TITLE
32-bit DW2 EH build

### ISSUE THREAD

**Issue by net147** [rubenvb/MinGW-w64-build-scripts#19]
Would it be possible to also have a 32-bit build with DW2 exception handling as default?

**Comment by rubenvb** [comment]
What would the exact problem be with sjlj? Are you experiencing bad performance or unexpected errors?

**Comment by net147** [comment]
Problem with SJLJ is performance penalty for the case when no exception is thrown for any section of code that calls a function that may throw an exception. This penalty occurs for function calls even if it is not contained in a try catch block. This makes calling functions that may throw exceptions slower.

**Comment by rubenvb** [comment]
I know that. Do you have concrete numbers that show more than a negligible difference? I'm inclined to believe the difference is not as bad as you think.

**Comment by net147** [comment]
In one application I've tested used for processing 3D models:
TDM 4.6.1 DW2: 22.231 seconds
TDM 4.6.1 SJLJ: 25.047 seconds

Exceptions are only used for handling I/O errors when reading/writing files.

**Comment by rubenvb** [comment]
After the reorganization of my Personal build directories on Sourceforge, you can find a 32-bit dw2 eh build of GCC 4.6.3 (accompanied by Clang 3.1 SVN, hence the name of the package). I would love to see the above benchmark repeated.

Link: http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/rubenvb/experimental/i686-w64-mingw32-clang-3.1_rubenvb.7z/download

**Comment by net147** [comment]
MinGW.org 4.4.0 DW2: 22.521 seconds
RB 4.6.3 DW2: 21.342 seconds
RB 4.6.3 DW2 Clang 3.1 SVN: 24.098 seconds
RB 4.6.3 SJLJ: 22.231 seconds
