### ISSUE TITLE
ninja support

### ISSUE THREAD

**Issue by martell** [rubenvb/MinGW-w64-build-scripts#26]
I'm playing with an idea in my head Ruben.

CMake 2.8.9-rc1 was released hours ago with ninja enabled by default.

Would it be possible to build the clang section with this build system?
Then eventually create a cmake script to build mingw64 all together. (not sure if gcc supports cmake)
Ninja should then make those builds much faster?

I want to plant ideas like jonforums lol

Your thoughts?

**Comment by rubenvb** [comment]
I see no reason to use CMake for LLVM/Clang. The Bash configure stuff works fine.

All of the stuff built for/with GCC uses configure/make as a build system; nothing else. That's the primary reason I chose to write plain shell scripts: no interlanguage problems (not that CMake has any interop problems with Bash).

Rewriting these scripts in CMake is well, a waste of time. I also see no advantage: I build on Linux, where Bash is about as fast as you can go. Is MSYS is slow, well, my scripts aren't the reason your build is going slowly.

Sorry, bad idea :)

**Comment by martell** [comment]
The only reason I mentioned using cmake is because that is the easiest way to create a ninja.build file.
Ninja would be faster than gnu make.
https://github.com/martine/ninja have a look and see for youself :)
You are correct in saying entering cmake into the mix is adding another dependency.

How long does a clang build vs a plain mingw build take for you?

**Comment by rubenvb** [comment]
What do you mean with "plain mingw build"? The build process will _always_ be limited by the speed of the compiler and linker. I'm quite sure 99% of the time building LLVM/Clang is spent in cc1plus (GCC's C++ backend). The other 1% is spent in CMake configure steps. ninja isn't going to change that. It may be great for incremental development builds and such, but that's not relevant here at all.

That being said, I do hope you know about Qt's "jom.exe" (included with the QtCreator binaries or seperately [here](ftp://ftp.qt.nokia.com/jom/)) which works with CMake generated MinGW Makefiles?

**Comment by martell** [comment]
By plain mingw build I was talking about building i686-mingw64 without llvm as a pose to with llvm.
That would make sense as I would hope it spends most of its time actually compiling and linking the files. :)

I've never seen jom before thanks for the tip dude.

So ninja would only be useful to a buildbot that does incremental builds or something of that sort?

Thanks for spending the time to reply to me by the way Ruben, I'm learning quite a lot here :)

**Comment by rubenvb** [comment]
Ah, well. If you want to compare Compiler/toolchain build times, this is what you want to compare:
GMP/MPFR/MPC/PPL/CLooG/Binutils/GCC(C and C++)/MinGW-w64
vs
Binutils/LLVM/Clang/MinGW-w64

Although that's not quite fair as Clang still needs GCC for linking and libstdc++/libgcc, so I need to build the whole shebang to get anything useful :(

Ninja is useful for people like its inventors: devs working on a huge project and wanting to test their latest code changes quickly. A buildbot would rebuild everything from the ground up every time to test the full source. So even for a buildbot ninja would be meh.

**Comment by martell** [comment]
Ahh I see. In the future what will llvm be linked against. Once it is stable and all that?

I was thinking if a build-bot didn't clean a directory there could be issues in the long run as I have learned myself all to well :/
I suppose you could have a bot that uses ninja to report back if the changes are good really quickly and then do a full build afterwards? Dunno how useful that would be though.
