### ISSUE TITLE
Updating one of your mingw-w64 personal builds to a newer GCC

### ISSUE THREAD

**Issue by cesss** [rubenvb/MinGW-w64-build-scripts#27]
Hi!

I've been using one of your mingw-w64 personal builds from the sourceforge page (4.6.3 to be exact) for years, and it has worked great (always from an OSX host in my case). I even compiled the source of your 4.6.3 build (in OSX) when I needed it, and it's always been fine.

However, many projects are moving to C++11 and C++14, so GCC 4.6.3 is becoming a bit old, and not suitable for building new projects. So, I'd wish to update to a newer mingw-w64 with a newer GCC.

Do you happen to have a package with all the source for a toolchain with a recent GCC, like you used to have in the sourceforge section of your personal builds?

Note that I use OSX as my development platform (10.12.6 in this moment) and I'll have to build your source from OSX (as I suppose you don't have precompiled darwin builds). In the past it was straightforward to build from source (for your 4.6.3 toolchain), so that's my main reason for asking here, because I always found it very easy to build.

Thanks!

**Comment by rubenvb** [comment]
Hi!
Great to hear my work is still useful after some years.
Unfortunately, I stopped updating my scripts and builds once MinGW-builds' and MSYS2's builds were able to replace them. For the most part, removing the isl bits and providing newer versions might work.

You've sparked my timewasting interest and I've gone ahead and fired up a build with the above suggestions. Only linux64mingw64 followed by a mingw64mingw combo. Just to see if GCC/binutils/gdb/mingw-w64 will still play nice.

**Comment by cesss** [comment]
Yes, your 4.6.3 personal build has been my mingw-w64 toolchain on OSX for quite a few years (and it still is).

Since I'm no expert at building toolchains, if you could give me some advice or point me to a simple list of steps I should follow for getting a new mingw-w64 with a modern GCC running on OSX, it would be greatly welcome. I find the mingw-w64 website written for either expert people at building toolchains, or for people who download a precompiled toolchain... but, honestly, I have no idea on how to set it up myself on OSX.

**Comment by rubenvb** [comment]
Well, these scripts themselves are relatively easy to follow. There are some variables being used, but most are set in the settings.sh script of the build*.sh scripts.

It's just not an easy procedure, and a lot of things can throw nonsensical errors at you. I'm pleasanatly amazed the scripts worked nicely for you. I'll see if I can get them working for GCC 7.1.

**Comment by cesss** [comment]
Given the time I use to keep my mingw-w64 toolchains (binaries last built in 2012), maybe GCC 6.4 would be a better choice than GCC 7.1 (as I suppose that 7.2 will come with a lot of bugfixes, while 6.4 can be considered very stable). Anyway, I didn't try GCC 6.x nor 7.x (most recent version I used is 5.x), so I really don't know if 6.4 can be considered more rock-solid than 7.1 (I'm just making a guess based on version numbers)

**Comment by rubenvb** [comment]
You can try:
https://github.com/rubenvb/MinGW-w64-build-scripts/releases/tag/7.1.0

It builds a linux64mingw64 combo, so it should also build one for Mac OS X. If you want GCC 6.4 instead, replace the src/gcc subdirectory contents with those of that version.

I can't guarantee much else beyond this point, I'm afraid, these things just take too much of my time to get 100% right ;).

**Comment by cesss** [comment]
Thanks a lot!! I'll try to build it, either today or tomorrow. I'll reply telling how it went.
